<?php
//if(!defined('authority')) {header("Location: ./404.html");}
//include_once "../../config/config.inc.php";
include_once "base.class.php";
class my extends base
{
    function __construct()
    {
        parent::__construct();
    }
    function __destruct()
    {
        //parent::__destruct(); // TODO: Change the autogenerated stub
        //        //子类中要重写构造覆盖父类的构造，可以避免数据库关闭
    }

    public function __get($pri_name){
        if(isset($this->$pri_name)){
            return $this->$pri_name;
        }else{
            return null;
        }
    }

    public function __set($pri_name,$value){
        $this->$pri_name = $value;
    }
    //得到用户的代理ID号
    function getAgencyId($somebody){
        $sql="select pid from anthority where username='".$somebody."'";
        $res = mysqli_query(parent::$conn,$sql);
        if($res){
            if(mysqli_num_rows($res) > 0){
                $row = mysqli_fetch_assoc($res);
                return $row["pid"];
            }else{
                mylog("getAgenctId err >>reference:".$somebody);
                return 0;//查无此人，，则置位根
            }
        }else{
            mylog("Login err:".mysqli_error(parent::$conn));
            return -3;//查询失败
        }
    }
    //得到用户的上级代理ID号
    function getPreAgencyId($somebody){
        $sql="select pid from anthority where username = (select reference from anthority where username='".$somebody."')";
        $res = mysqli_query(parent::$conn,$sql);
        if($res){
            if(mysqli_num_rows($res) > 0){
                $row = mysqli_fetch_assoc($res);
                return $row["pid"];
            }else{
                mylog("getAgenctId err >>reference:".$somebody);
                return 0;//没有上级代理，则置位根
            }
        }else{
            mylog("Login err:".mysqli_error(parent::$conn));
            return -3;//查询失败
        }
    }

    function Login($username,$password)
    {
        if (empty($username) || empty($password)) {
            return -5;//用户名/密码/推荐人不能为空
        } else {
            $sql = "select flag,pid  from anthority where username='" . $username . "' and password='" . $password . "'";
            $res = mysqli_query(parent::$conn, $sql);
            if ($res) {
                if (mysqli_num_rows($res) > 0) {
                    $row = mysqli_fetch_assoc($res);
                    if ($row["flag"] == 1) {
                        return 1;//成功登陆
                    } else {
                        return -2;//账号异常冻结
                    }
                } else {
                    return -1;//查无此人
                }
            } else {
                mylog("Login err:" . mysqli_error(parent::$conn));
                return -3;//查询失败
            }
        }
    }


//检查
    function checkReg($username){
        //注册时合法性检查
        $sql = "select * from anthority where username='".$username."'";
        $res = mysqli_query(parent::$conn,$sql);
        if($res) {
            if (mysqli_num_rows($res) == 0) {
                return 1;//通过
            }else{
                return -1;//已经注册过了
            }
        }else{
            return -2;//数据库问题
            mylog("checkReg err:".mysqli_error(parent::$conn));
        }
    }
    function register($username,$password,$reference){

        $reference =  empty($reference) ?0 :$reference;
        if(empty($username) || empty($password)){
            return -2;//用户名/密码不能为空
        }else{
            $i = $this->checkReg($username);
            if($i == -1){return -1;}//重复注册
            if($i == -2){return -7;}//合法性检查数据库出错
            if($i == 1)
                {
                            /***账户表里插入***/
                            $sql1 = "insert into anthority(username,password,pid,reference,registerTime,flag)
                                values ('".$username."','".$password."','".$username."','".$reference."','".date("Y-m-d H:i:s")."',1)";
                            $res1 = mysqli_query(parent::$conn,$sql1);
                            if ($res1) {
                                return 1;
                            } else {
                                mylog("注册数据库插入失败,>>>sql1:" . $sql1);
                                return -6;
                            }
                }
            }
    }



    function getAgencyList($username){
        $agencyList =array();
        $sql="select username,registerTime,flag from anthority where reference ='".$username."'";
        $res = mysqli_query(parent::$conn,$sql);
        if($res){
            if(mysqli_num_rows($res) > 0){
                while($row=mysqli_fetch_assoc($res)){
                        $agency["agencyName"] = $row["username"];
                        $agency["regTime"] = date('m/d',strtotime($row["registerTime"]));
                        $agency["flag"] = $row["flag"] ? '正常' : '冻结';
                    array_push($agencyList,json_encode($agency,JSON_UNESCAPED_UNICODE));
                }
            }else return 0;
        }else return -1;//数据库错误
        return $agencyList;
    }

    function getShareLink($reference){//获取自己的推广短链接
        $yourLongUrl = "http://jingfenzhushou.com/lousi/application/view/main.html?reference=".$reference;
        $url = 'https://api.weibo.com/2/short_url/shorten.json?source='.Sina_appKey.'&url_long='.$yourLongUrl;
        $data = httpGet($url);
        //print_r($data);
        $dataObj = json_decode($data);
        if(property_exists($dataObj,'urls')){
            if($dataObj->urls[0]->result){
                return $dataObj->urls[0]->url_short;
            }
        }
        return -1;
    }
}
